// Fake but faithful slices of the real catalog (keel/catalog/*.yaml) and reports/.
window.KEEL_DATA = {
  enums: {
    harm: ["wrong-decision","data-exposed","code-execution","downtime","reputation-legal"],
    surface: ["user-agent","agent-agent","agent-environment"],
    source: ["external-attacker","internal","hallucination","error","accident","training-data"],
    component: ["model","tool","downstream","memory","knowledge-base","identity-store"],
    nature: ["targeted","secondary"],
    strength: ["gating","soft"],
    mitigation_class: ["gating_control","detector","process","evidential_mitigation","corrective"],
    status: ["draft","verified"],
  },
  stats: { threats: 13, mitigations: 71, links: 96, systems: 2, verified: 44, implementations_recorded: 9 },
  coverage: {
    overall: 68,
    entities: [
      { entity: "threat", overall: 74, fields: [
        { name: "threat.weaknesses", pct: 100 }, { name: "threat.harm", pct: 100 },
        { name: "threat.reachability", pct: 62 }, { name: "threat.references", pct: 15 },
        { name: "threat.mitre_id", pct: 0, orphan: true } ] },
      { entity: "mitigation", overall: 61, fields: [
        { name: "mitigation.purpose", pct: 100 }, { name: "mitigation.control_mechanism", pct: 88 },
        { name: "mitigation.failure_behavior", pct: 54 }, { name: "mitigation.implementations", pct: 13 } ] },
    ],
  },
  gaps: [
    { name: "Threats with no mitigation", desc: "Nothing addresses these yet — a floor, not a failure.", ids: ["T-METADATA-LEAK","T-TOXIC"] },
    { name: "Threats missing a weakness", desc: "A threat must rest on at least one architectural condition.", ids: ["T-SHADOW-AI"] },
    { name: "Dangling mitigation links", desc: "The link points at a card that no longer exists.", ids: ["T-DOS :: CTRL-LEGACY-GUARD"] },
  ],
  activity: [
    { msg: "Add threat: tool description poisoning", meta: "jane · 2 days ago · 4f2a9c1" },
    { msg: "Tighten reachability on T-TOOL-ABUSE", meta: "sam · 3 days ago · 91be03d" },
    { msg: "Record implementation for CTRL-HUMAN-IN-LOOP", meta: "jane · 6 days ago · 27dd14a" },
  ],
  threats: [
    { id: "T-TOOL-ABUSE", title: "Unauthorized or destructive tool action", harm: "code-execution",
      surface: ["agent-environment","user-agent"], source: ["external-attacker","hallucination"], tags: [],
      reachability: "NOT applicable if the reachable tools have no operations with real consequences (read-only, no side effects), or the model influences neither the choice of tool nor its arguments (a rigidly predefined pipeline).",
      weaknesses: [
        { component: "tool", nature: "targeted", text: "A reachable tool performs destructive/irreversible or privileged operations (delete, admin, exec, persistent side effects), and the call is initiated by the model with no out-of-model authorization on the action itself." },
        { component: "tool", nature: "targeted", text: "Arguments or the choice of action are formed by the model and hijacked via injection or agent goal substitution; the tool performs an action the user did not request." },
        { component: "tool", nature: "targeted", text: "A tool with terminal/shell access is invoked on the model's initiative — a direct path to RCE." },
        { component: "tool", nature: "targeted", text: "The confirmation mechanism (HITL) is not risk-differentiated and is devalued by a stream of identical requests: a critical action is approved mechanically." } ],
      mitigations: [
        { id: "CTRL-TOOL-ALLOWLIST", strength: "gating", rationale: "An allowlist of permitted tools limits exposure of destructive operations to only those tools the agent actually needs" },
        { id: "CTRL-IRREVERSIBLE-ACTION-GUARD", strength: "gating", rationale: "A guard against irreversible actions requires additional confirmation and logging" },
        { id: "CTRL-HACT-CRITICAL", strength: "gating", rationale: "Mandatory human confirmation for critical tools ensures that fatigue does not lead to critical actions being missed" },
        { id: "CTRL-INPUT-FILTERING", strength: "soft", rationale: "Filtering input for prompt injection" },
        { id: "CTRL-PROMPT-HARDENING", strength: "soft", rationale: "Hardening the system prompt separates instructions from external content" } ],
      references: [], lastChanged: "Last changed 3 days ago by sam" },
    { id: "T-DATA-LEAK", title: "Sensitive data leaves through the agent", harm: "data-exposed",
      surface: ["user-agent"], source: ["external-attacker","hallucination"], tags: ["pii"],
      reachability: "NOT applicable if the agent has no read path to data the requesting principal is not already entitled to.",
      weaknesses: [
        { component: "downstream", nature: "targeted", text: "A retrieval tool carries a broad service token, so scoping depends entirely on the token rather than on the requesting principal." },
        { component: "memory", nature: "secondary", text: "Conversation memory persists across principals, so data from one session can be surfaced in another." } ],
      mitigations: [
        { id: "CTRL-DATA-ACCESS-CONTROL", strength: "gating", rationale: "Per-principal scoping at the data layer stops a broad token from widening the read path" },
        { id: "CTRL-DLP", strength: "soft", rationale: "Egress inspection catches known-shape secrets after the fact" } ],
      references: [{ id: "LLM02", url: "https://owasp.org/www-project-top-10-for-large-language-model-applications/" }],
      lastChanged: "Last changed 9 days ago by jane" },
    { id: "T-CMD-INJECT", title: "Command injection through a tool", harm: "code-execution",
      surface: ["agent-environment"], source: ["external-attacker"], tags: [],
      reachability: "NOT applicable if no tool reaches an interpreter, a shell, or a code-execution runtime.",
      weaknesses: [{ component: "tool", nature: "targeted", text: "A tool concatenates model output into a shell or interpreter invocation rather than passing parameterized arguments." }],
      mitigations: [{ id: "CTRL-COMMAND-SANDBOX", strength: "gating", rationale: "A command allowlist restricts the tool's executable actions" },
        { id: "CTRL-INPUT-PARAMETERIZATION", strength: "gating", rationale: "Parameterized calls instead of string concatenation prevent injection" }],
      references: [], lastChanged: "Last changed 3 weeks ago by sam" },
    { id: "T-METADATA-LEAK", title: "Metadata discloses more than the answer", harm: "data-exposed",
      surface: ["user-agent"], source: ["error"], tags: [], reachability: "",
      weaknesses: [{ component: "model", nature: "secondary", text: "Tool-call traces and citations are returned verbatim, exposing internal identifiers and paths." }],
      mitigations: [], references: [], lastChanged: "Last changed 5 weeks ago by jane" },
    { id: "T-SSRF", title: "Agent-driven request forgery", harm: "data-exposed",
      surface: ["agent-environment"], source: ["external-attacker"], tags: [],
      reachability: "NOT applicable if no tool accepts a URL or host derived from model output.",
      weaknesses: [{ component: "tool", nature: "targeted", text: "A fetch tool takes its target host from model output with no allowlist, so internal endpoints are reachable." }],
      mitigations: [{ id: "CTRL-URL-ALLOWLIST", strength: "gating", rationale: "An egress allowlist prevents the agent reaching internal endpoints" }],
      references: [], lastChanged: "Last changed 4 days ago by sam" },
    { id: "T-DOS", title: "Resource exhaustion through the agent loop", harm: "downtime",
      surface: ["user-agent"], source: ["external-attacker","accident"], tags: [],
      reachability: "NOT applicable if the agent runs bounded, pre-paid work with a hard iteration cap.",
      weaknesses: [{ component: "model", nature: "targeted", text: "The agent loop has no iteration or token ceiling, so one request can consume unbounded compute." }],
      mitigations: [{ id: "CTRL-ITERATION-LIMITS", strength: "gating", rationale: "A hard iteration ceiling bounds the loop" },
        { id: "CTRL-LEGACY-GUARD", strength: "soft", rationale: "Legacy throttle (card removed from the catalog)" }],
      references: [], lastChanged: "Last changed 2 months ago by jane" },
    { id: "T-SHADOW-AI", title: "Unsanctioned model or tool in the path", harm: "reputation-legal",
      surface: ["agent-environment"], source: ["internal"], tags: ["governance"], reachability: "",
      weaknesses: [], mitigations: [{ id: "CTRL-SHADOW-AI-POLICY", strength: "soft", rationale: "Policy plus discovery narrows unsanctioned use" }],
      references: [], lastChanged: "Last changed 6 weeks ago by sam" },
  ],
  mitigations: [
    { id: "CTRL-TOOL-ALLOWLIST", name: "Tool allowlist", mitigation_class: "gating_control", status: "verified",
      purpose: "Restrict the agent to the smallest set of tools its task actually needs, so destructive operations are not reachable at all.",
      scope: "Every agent runtime that resolves a tool registry at session start.",
      control_mechanism: "The runtime resolves tool names against a static per-agent allowlist before dispatch. A name outside the list is refused without reaching the tool layer.",
      failure_behavior: "Fail closed: an unlisted tool call is refused and logged as a policy event.",
      implementations: [{ name: "Gateway tool policy", owner: "Platform Security", note: "Allowlist lives in the agent manifest, enforced at the gateway." }],
      addresses: ["T-TOOL-ABUSE","T-CMD-INJECT"] },
    { id: "CTRL-HACT-CRITICAL", name: "Human confirmation for critical actions", mitigation_class: "process", status: "verified",
      purpose: "Put a person in front of any action whose consequences cannot be undone.",
      scope: "Tools classified critical: money movement, deletion, privilege change.",
      control_mechanism: "The runtime blocks on an explicit approval for any tool tagged critical, showing the resolved arguments rather than the model's intent.",
      failure_behavior: "Fail closed: no approval, no call.",
      implementations: [], addresses: ["T-TOOL-ABUSE"] },
    { id: "CTRL-IRREVERSIBLE-ACTION-GUARD", name: "Irreversible action guard", mitigation_class: "gating_control", status: "draft",
      purpose: "Require a second, out-of-model signal before an action that cannot be reversed.",
      scope: "Any tool with persistent external side effects.",
      control_mechanism: "A guard evaluates the resolved call against an irreversibility classifier and demands a second factor — a ticket, a countersignature, or a delay window.",
      failure_behavior: "Fail closed.", implementations: [], addresses: ["T-TOOL-ABUSE"] },
    { id: "CTRL-DATA-ACCESS-CONTROL", name: "Per-principal data access control", mitigation_class: "gating_control", status: "verified",
      purpose: "Scope every read to the principal who asked, not to the service the tool runs as.",
      scope: "All retrieval and lookup tools.",
      control_mechanism: "The gateway mints a per-session token carrying the end principal; downstream services authorize against that token only.",
      failure_behavior: "Fail closed: an out-of-scope lookup returns 403 before it reaches the service.",
      implementations: [{ name: "Session-scoped gateway tokens", owner: "Platform Security", note: "Rolled out to all storefront agents." }],
      addresses: ["T-DATA-LEAK"] },
    { id: "CTRL-INPUT-FILTERING", name: "Input filtering", mitigation_class: "detector", status: "draft",
      purpose: "Detect known injection and jailbreak shapes before they enter context.",
      scope: "User input and free-form tool output.",
      control_mechanism: "A classifier scores each untrusted span; high-scoring spans are stripped or quarantined.",
      failure_behavior: "Fail open — this is a detector, not a gate. It lowers likelihood and never closes the path.",
      implementations: [], addresses: ["T-TOOL-ABUSE","T-CMD-INJECT"] },
    { id: "CTRL-DLP", name: "Egress inspection", mitigation_class: "detector", status: "draft",
      purpose: "Catch known-shape secrets on the way out.",
      scope: "Agent responses and outbound tool payloads.",
      control_mechanism: "Pattern and entropy matching over egress content, with redaction on match.",
      failure_behavior: "Fail open. Detection only.", implementations: [], addresses: ["T-DATA-LEAK"] },
  ],
  styleFields: [
    { entity: "threat", field: "title", pct: 100 },
    { entity: "threat", field: "harm", pct: 100 },
    { entity: "threat", field: "weaknesses[].text", pct: 100 },
    { entity: "threat", field: "reachability", pct: 62,
      slots: { purpose: "Say when this threat is NOT a live path, judged on the un-mitigated architecture.",
        include: ["Open with “NOT applicable if”.","The architectural fact that removes the path.","The asset-materiality carve-out, when there is one."],
        avoid: ["A control that mitigates the threat — that belongs in mitigations.","Hedging (“probably not applicable”).","More than two carve-outs in one field."],
        example: "NOT applicable if the reachable tools have no operations with real consequences (read-only, no side effects)." } },
    { entity: "threat", field: "references[]", pct: 15 },
    { entity: "threat", field: "mitre_id", pct: 0, orphan: true },
    { entity: "mitigation", field: "purpose", pct: 100 },
    { entity: "mitigation", field: "control_mechanism", pct: 88 },
    { entity: "mitigation", field: "failure_behavior", pct: 54 },
    { entity: "mitigation", field: "implementations[]", pct: 13 },
  ],
  reports: [
    { system_id: "checkout-agent", system_name: "Checkout Agent", latest_date: "2026-08-26", report_count: 2, top_severity: "critical" },
    { system_id: "docs-assistant", system_name: "Docs Assistant", latest_date: "2026-07-02", report_count: 1, top_severity: "low" },
  ],
  report: {
    system_id: "checkout-agent", system_name: "Checkout Agent", date: "2026-08-26",
    assessor: "Jane Doe <jane@example.com>",
    system_description: "Answers storefront checkout questions, looks up order status, and now issues refunds under a value cap via the payments API.",
    delta_summary: "Refunds were added as an agent tool. Re-assessed the payment path only; the order-lookup findings from 2026-05-10 were re-checked and the access-control gap is now closed.",
    findings: [
      { id: "T-TOOL-ABUSE", severity: "critical", likelihood: "high", harm: "wrong-decision",
        scenario: "A shopper talks the agent into refunding an order that was never returned; the refund tool fires on model judgement alone and the money leaves before anyone reviews it.",
        source: { who: "external-attacker", motive: "free goods plus a refund", access: "the public storefront chat" },
        asset: "refund budget and the payments API", attack_surface: "user-agent", complexity: "low",
        vulnerability: "the refund tool executes on model decision with no human gate and no check that a return was actually received",
        reasoning: "irreversible money movement, reachable anonymously, and the only thing standing in the way is model judgement",
        delta: "new: no prior agent path could move money; refunds previously required a support agent in the admin console",
        requirements: [
          { id: "CTRL-HACT-CRITICAL", status: "needs_implementation" },
          { id: "CTRL-IRREVERSIBLE-ACTION-GUARD", status: "needs_implementation" },
          { id: null, status: "needs_implementation", description: "Refuse a refund unless the warehouse system has recorded the return against that order id." } ],
        ignored: [{ id: "CTRL-RATE-LIMITING", reason: "throttling slows a refund spree but does not stop the first fraudulent refund, which is already the loss" }] },
      { id: "T-DATA-LEAK", severity: "medium", likelihood: "low", harm: "data-exposed",
        scenario: "A shopper asks about another customer order; the agent looks it up and reads back the address and line items.",
        source: { who: "external-attacker", motive: "harvest customer PII", access: "the public storefront chat" },
        asset: "customer order records (name, address, line items)", attack_surface: "user-agent", complexity: "medium",
        vulnerability: "the orders tool takes an order id from model output; scoping depends entirely on the token the tool carries",
        reasoning: "the token is now session-scoped at the gateway, so a cross-customer lookup returns 403 before it reaches the orders service",
        delta: "unchanged by the refund work; carried forward from 2026-05-10 to record that the gap closed",
        requirements: [{ id: "CTRL-DATA-ACCESS-CONTROL", status: "already_covered",
          note: "Closed since the last assessment: the shared API gateway now mints per-session tokens for every storefront agent, so the orders service never sees a broad token." }],
        ignored: [] } ],
    discarded: [
      { id: "T-CMD-INJECT", reason: "no interpreter, shell or code-execution tool in this deployment" },
      { id: "T-SSRF", reason: "the agent calls two fixed internal endpoints; no tool takes a URL from model output" } ],
    dialogue: [
      { q: "Is there a value cap on the refund tool, and who set it?", a: "Payments caps it at 200 EUR per call. Nothing caps calls per session.",
        impact: "Kept the threat at critical: the cap bounds one refund, not a sequence of them, so the loss is not actually bounded." },
      { q: "Does anything verify the goods came back before a refund goes out?", a: "No. The agent trusts what the shopper says in chat.",
        impact: "Added the ad hoc requirement about checking the warehouse return record, since no catalog control covers this business rule." },
      { q: "Would rate limiting be enough here?", a: "No, the first fraudulent refund is already the loss. Do not list it as a mitigation.",
        impact: "Moved CTRL-RATE-LIMITING to ignored with that reasoning rather than listing it as a partial control." } ],
  },
};
